parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: edusoho
    database_user: root
    database_password: 'root'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: zh_CN
    secret: q72j3pa7dg0c4scsgs04wk8wgos4gws
    user_partner: none